/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pruebasinlocalhost;

import java.io.File;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author MERRY
 */
public class VistaI extends javax.swing.JFrame {

    /**
     * Creates new form VistaI
     */
    public String BaseDatos = "ganadero";
    public String contenido;
    public VistaI() {
        initComponents();
        contenido = "# To change this license header, choose License Headers in Project Properties.\n"
                        + "# To change this template file, choose Tools | Templates\n"
                        + "# and open the template in the editor.\n"
                        + "\n"
                        + "#servidor=RASPBERRYPI\n"
                        + "#usuario=uproy\n"
                        + "#clave=123456\n"
                        + "#baseDeDatos=ganadero\n"
                        + "\n"
                        + "servidor=localhost\n"
                        + "usuario=root\n"
                        + "clave=\n"
                        + "baseDeDatos=" + BaseDatos + "\n"
                        + "EncabezadosCargaMasivaAnimal=NUM_ANIMAL,NUM_MADRE,SEXO,HIERRO,HIERRO_C,NUM_PARTOS,CAPADO,DESCORNADO,IMPLANTE,PESO,FEC_NACIMIENTO,DESTETE,FEC_DESTETE,PESO_DESTETE,NOTAS,GRUPO\n"
                        + "EncabezadosCargaMasivaPesaje=NUM,NUM_MAMA,NUM_HIJO,SEXO,HIERRO,FEC_DESTETE,PESO_ANT,TIPO_PESAJE,PESO,DIF\n"
                        + "EncabezadosCargaMasivaPalpacion=CHECK,NUM,NUM_MAMA,NUM_HIJO,PARTO,HIERRO,FEC_NOVILLA,F.U.P,ULT_PALPACION,ESTADO_ANT,NUM_MESES_ANT,TRATAMIENTO,ESTADO,NUM_MESES";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lblmensaje = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Prueba de Conexion");

        jButton1.setText("Probar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jButton1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        lblmensaje.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblmensaje.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblmensaje.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblmensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(jButton1)))
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(203, 203, 203))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1)
                .addGap(48, 48, 48)
                .addComponent(jButton1)
                .addGap(35, 35, 35)
                .addComponent(lblmensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Coneccion con = new Coneccion();
        int resp = con.ConectarInicial();
        String mensaje= "";
        if(resp == 10){
            mensaje = "Por favor instale el servidor XAMPP ó Inicie el servicio de Mysql ... Pro favro revice el tutorial para colocar servicio mysql automatico";
            lblmensaje.setText("respuesta de conexion: "+resp+"\n"+mensaje);
        }
        else if(resp == 11){
            mensaje = "Hay error al momento de acceder al servidor, por favor cambiar la informacion de configuracion o contatac con el administrador del sistema e intentelo nuevamente.";
            lblmensaje.setText("respuesta de conexion: "+resp+"\n"+mensaje);
        }
        else if(resp == 13){
            boolean create = con.ConectarSinBD(BaseDatos);
            if(create){
                CargarArchivoCoonfiguracion(BaseDatos);
                try {
                    CargaEsquemaBD();
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(VistaI.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(VistaI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            mensaje = "<html><body><p>El sistema ya se encuentra con la configuracion inicial instalada</p><br><p>por favor importar la base de datos desde el sistema de ganaderia, para que el sistema este actualizado.</p></body></html>";
            lblmensaje.setText(mensaje);
        }
        else{
            mensaje = "<html><body><p>El sistema ya se encuentra con la configuracion inicial instalada</p></br><p>por favor importar la base de datos desde el sistema de ganaderia, para que el sistema este actualizado.</p></body></html>";
            lblmensaje.setText(mensaje);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jButton1AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1AncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblmensaje;
    // End of variables declaration//GEN-END:variables

    public void CargarArchivoCoonfiguracion(String bd) {
        String rut = "C://CONFIG GANADERIASS";
        File archivo = new File(rut);
        if (archivo.exists()) {
//            if (archivo.isFile()) System.out.println("Es un archivo");
//            if (archivo.isDirectory()) System.out.println("Es una carpeta");
            String ruta = rut + "//Config.properties";
            CreacionArchivo cre = new CreacionArchivo();
            boolean arcConfig = cre.CrearArchivo(ruta, contenido);
            System.out.println("arcConfig-->" + arcConfig);
        } else {
            if (archivo.mkdirs()) {
                String ruta = rut + "//Config.properties";
               
                CreacionArchivo cre = new CreacionArchivo();
                boolean arcConfig = cre.CrearArchivo(ruta, contenido);
                System.out.println("arcConfig-->" + arcConfig);
            } else {
                System.out.println("Error al crear directorio");
            }
            System.out.println("OJO: ¡¡No existe el archivo de configuración!!");
        }
    }

    private void CargaEsquemaBD() throws ClassNotFoundException, SQLException {
        Coneccion con = new Coneccion();

        ArrayList<String> consultas = new ArrayList<>();
//        SET SQL_MODE = \"NO_AUTO_VALUE_ON_ZERO\";\n" +
//                        "SET AUTOCOMMIT = 0;\n" +
//                        "START TRANSACTION;\n" +
//                        "SET time_zone = \"+00:00\";
        //<editor-fold defaultstate="collapsed" desc="Procedimientos">
//        consultas.add("DROP PROCEDURE IF EXISTS `actualizarPesos`");
        consultas.add("CREATE DEFINER=`root`@`localhost` PROCEDURE `actualizarPesos` (IN `_idAnimal` INT(20), IN `_sisuser` INT(20))  BEGIN    \n"
                + "	DECLARE _id INT(20) DEFAULT 0;\n"
                + "	DECLARE _Leng INT(20) DEFAULT 0;\n"
                + "	DECLARE _peso DOUBLE DEFAULT 0;\n"
                + "	DECLARE _pesoA DOUBLE DEFAULT 0;\n"
                + "	DECLARE _cons INT(3) DEFAULT -1;	-- Variable para controlar el fin del bucle	\n"
                + "	DECLARE fin INTEGER DEFAULT 0;  -- El SELECT que vamos a ejecutar\n"
                + "	DECLARE pesos_cursor CURSOR FOR \n"
                + "		SELECT id, peso FROM pesaje WHERE id_animal = _idAnimal\n"
                + "		ORDER BY fecha_pesado ASC;\n"
                + "	DECLARE CONTINUE HANDLER FOR NOT FOUND SET fin=1;   -- CondiciÃ³n de salida \n"
                + "	SELECT COUNT(*)-1 FROM pesaje WHERE id_animal = _idAnimal\n"
                + "		ORDER BY fecha_pesado ASC\n"
                + "		INTO _Leng;\n"
                + "	OPEN pesos_cursor;\n"
                + "	get_pesos: LOOP\n"
                + "		IF fin = 1 THEN\n"
                + "			LEAVE get_pesos;\n"
                + "		END IF;\n"
                + "		SET  _cons = _cons + 1;\n"
                + "		IF _Leng < _cons THEN\n"
                + "			LEAVE get_pesos;\n"
                + "		END IF;\n"
                + "		FETCH pesos_cursor INTO _id, _peso;	\n"
                + " 		IF _cons > 0 THEN\n"
                + "			UPDATE `pesaje`\n"
                + "			SET  `peso_anterior` = _pesoA,\n"
                + "			`id_usuario` = _sisuser\n"
                + "			WHERE `id` = _id;\n"
                + "		END IF;		\n"
                + "		SET _pesoA = _peso;\n"
                + "		END LOOP get_pesos;\n"
                + "	CLOSE pesos_cursor;		\n"
                + "    END");
//</editor-fold>

        //<editor-fold defaultstate="collapsed" desc="FUNCIONES">
        consultas.add("CREATE DEFINER=`root`@`localhost` FUNCTION `MascaraMonedaDecimal` (`dato` VARCHAR(255)) RETURNS VARCHAR(255) CHARSET latin1 COLLATE latin1_spanish_ci BEGIN \n"
                + "	DECLARE valor_ret VARCHAR(255) default '';\n"
                + "	DECLARE entero VARCHAR(255) default '';\n"
                + "	DECLARE decim VARCHAR(255) default '';\n"
                + "	DECLARE tamentero int(20) default 0;\n"
                + "	declare poscoma int(20) default 0;\n"
                + "	declare i int(10) default 0;\n"
                + "	declare con int(10) default 0;\n"
                + "	SET entero = SPLIT_STR(dato, ',', 1);		\n"
                + "	SET poscoma = POSITION(',' in dato);\n"
                + "	if (poscoma > 0) then\n"
                + "		SET decim = SPLIT_STR(dato, ',', 2);\n"
                + "	end if;\n"
                + "	set tamentero = length(entero);\n"
                + "	set i = tamentero;\n"
                + "	while i > 0 do\n"
                + "		if (mod(con, 3) = 0 and con > 0) then\n"
                + "				set valor_ret = concat('.', valor_ret);\n"
                + "				set con = 0;\n"
                + "		end if;\n"
                + "		SET valor_ret = CONCAT(substring(entero, i, 1), valor_ret);\n"
                + "		set con = con + 1;\n"
                + "		set i = i - 1;\n"
                + "	end while;\n"
                + "	\n"
                + "	if (decim <> '') then\n"
                + "		SET valor_ret = CONCAT(valor_ret, ',', decim);\n"
                + "	end if;\n"
                + "    RETURN valor_ret;\n"
                + "END");

        consultas.add("CREATE DEFINER=`root`@`localhost` FUNCTION `NumeroHijos` (`num_mom` VARCHAR(100), `opc` INT(10)) RETURNS VARCHAR(100) CHARSET latin1 COLLATE latin1_spanish_ci BEGIN\n"
                + "DECLARE valor_ret VARCHAR(100) DEFAULT NULL;\n"
                + "\n"
                + "IF (opc = 0) THEN\n"
                + "SELECT COUNT(*) SUMAHIJOS\n"
                + "FROM animales WHERE numero_mama = num_mom\n"
                + "INTO valor_ret;\n"
                + "ELSEIF (opc = 1) THEN\n"
                + "SELECT MAX(`fecha_nacimiento`)  FROM animales\n"
                + "WHERE numero_mama =  num_mom\n"
                + "INTO valor_ret;\n"
                + "ELSE\n"
                + "SELECT numero FROM animales\n"
                + "WHERE (numero_mama =  num_mom OR numero_mama_adoptiva = num_mom) AND numero <> num_mom\n"
                + "ORDER BY id DESC\n"
                + "LIMIT 1\n"
                + "INTO valor_ret;\n"
                + "END IF;\n"
                + "\n"
                + "   RETURN valor_ret;\n"
                + "END");

        consultas.add("CREATE DEFINER=`root`@`localhost` FUNCTION `NumeroPartos` (`num_mom` VARCHAR(100)) RETURNS VARCHAR(100) CHARSET latin1 COLLATE latin1_spanish_ci BEGIN\n"
                + "DECLARE valor_ret VARCHAR(100) DEFAULT NULL;\n"
                + "SELECT COUNT(*) FROM (\n"
                + "	SELECT tabla.fecha, COUNT(tabla.fecha)\n"
                + "	FROM (\n"
                + "	SELECT id,fecha_nacimiento fecha\n"
                + "	FROM animales\n"
                + "	WHERE numero_mama = num_mom\n"
                + "	) tabla\n"
                + "	GROUP BY tabla.fecha\n"
                + "	) tabla2\n"
                + "	INTO valor_ret;\n"
                + "   RETURN valor_ret;\n"
                + "END");

        consultas.add("CREATE DEFINER=`root`@`localhost` FUNCTION `NumMeses` (`estado` VARCHAR(100), `num` INT(10), `fecha_palpacion` DATE) RETURNS INT(100) BEGIN\n"
                + "DECLARE valor_ret INT(10) DEFAULT 0;\n"
                + "DECLARE numdias INT(10) DEFAULT 0;\n"
                + "DECLARE nummeses INT(10) DEFAULT 0;\n"
                + "\n"
                + "IF (estado = 'preÃ±ada') THEN\n"
                + "SELECT DATEDIFF(NOW(), `fecha_palpacion`)\n"
                + "INTO numdias;\n"
                + "\n"
                + "SET nummeses = numdias/30;\n"
                + "SET valor_ret = nummeses + num;\n"
                + "END IF;\n"
                + "   RETURN valor_ret;\n"
                + "END");

        consultas.add("CREATE DEFINER=`root`@`localhost` FUNCTION `SPLIT_STR` (`X` VARCHAR(255), `delim` VARCHAR(12), `pos` INT) RETURNS VARCHAR(255) CHARSET latin1 COLLATE latin1_spanish_ci BEGIN \n"
                + "    RETURN REPLACE(SUBSTRING(SUBSTRING_INDEX(X, delim, pos),\n"
                + "       LENGTH(SUBSTRING_INDEX(X, delim, pos -1)) + 1),\n"
                + "       delim, '');\n"
                + "END");
//</editor-fold>

        //<editor-fold defaultstate="collapsed" desc="Tablas">
        
        consultas.add("DROP TABLE IF EXISTS `actividades`;");
        
        consultas.add("CREATE TABLE `actividades` (\n"
                + "  `id` int(50) NOT NULL,\n"
                + "  `descripcion` varchar(550) COLLATE latin1_spanish_ci DEFAULT NULL,\n"
                + "  `estado` enum('Activo','Inactivo') COLLATE latin1_spanish_ci DEFAULT NULL,\n"
                + "  `fecha_registro` datetime DEFAULT NULL,\n"
                + "  `usuario` int(50) DEFAULT NULL\n"
                + ") ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_spanish_ci;");

        consultas.add("CREATE TABLE `animales` (\n"
                + "  `id` int(50) NOT NULL,\n"
                + "  `id_tipo_animal` int(50) DEFAULT NULL,\n"
                + "  `hierro` int(50) DEFAULT NULL,\n"
                + "  `numero` varchar(100) COLLATE latin1_spanish_ci DEFAULT NULL,\n"
                + "  `numero_descendiente` int(2) DEFAULT NULL,\n"
                + "  `estado_descendiente` int(1) DEFAULT 0,\n"
                + "  `numero_mama` varchar(100) COLLATE latin1_spanish_ci DEFAULT NULL,\n"
                + "  `numero_mama_adoptiva` varchar(100) COLLATE latin1_spanish_ci DEFAULT NULL,\n"
                + "  `peso` double DEFAULT 0,\n"
                + "  `genero` enum('macho','hembra') COLLATE latin1_spanish_ci DEFAULT NULL,\n"
                + "  `grupo` int(50) DEFAULT NULL,\n"
                + "  `calificacion` text COLLATE latin1_spanish_ci DEFAULT NULL,\n"
                + "  `notas` text COLLATE latin1_spanish_ci DEFAULT NULL,\n"
                + "  `fecha_destete` date DEFAULT NULL,\n"
                + "  `capado` enum('1','0') COLLATE latin1_spanish_ci DEFAULT NULL,\n"
                + "  `fecha_nacimiento` date DEFAULT NULL,\n"
                + "  `muerte` enum('1','0') COLLATE latin1_spanish_ci DEFAULT '0',\n"
                + "  `peso_destete` double NOT NULL,\n"
                + "  `destete` enum('0','1') COLLATE latin1_spanish_ci DEFAULT NULL,\n"
                + "  `fecha_muerte` date DEFAULT NULL,\n"
                + "  `descripcion_muerte` text COLLATE latin1_spanish_ci DEFAULT NULL,\n"
                + "  `venta` enum('1','0') COLLATE latin1_spanish_ci DEFAULT '0',\n"
                + "  `fecha_venta` date DEFAULT NULL,\n"
                + "  `tipo_venta` enum('particular','matadero') COLLATE latin1_spanish_ci DEFAULT 'particular',\n"
                + "  `precio_venta` double DEFAULT NULL,\n"
                + "  `peso_canal` double DEFAULT NULL,\n"
                + "  `fecha_novilla` date NOT NULL,\n"
                + "  `hierro_fisico` enum('0','1') COLLATE latin1_spanish_ci NOT NULL,\n"
                + "  `implante` enum('0','1') COLLATE latin1_spanish_ci NOT NULL,\n"
                + "  `descornado` enum('0','1') COLLATE latin1_spanish_ci NOT NULL,\n"
                + "  `fecha` datetime DEFAULT NULL,\n"
                + "  `id_usuario` int(50) DEFAULT NULL\n"
                + ") ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_spanish_ci;");

        consultas.add("CREATE TABLE `animalesxhierro` (\n"
                + "  `id` int(50) NOT NULL,\n"
                + "  `id_propietario` int(50) DEFAULT NULL,\n"
                + "  `id_animal` int(50) DEFAULT NULL,\n"
                + "  `estado` enum('Activo','Inactivo') COLLATE latin1_spanish_ci DEFAULT NULL,\n"
                + "  `fecha` datetime DEFAULT NULL,\n"
                + "  `id_usuario` int(50) DEFAULT NULL\n"
                + ") ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_spanish_ci;");

        consultas.add("CREATE TABLE `bloques` (\n"
                + "  `id` int(50) NOT NULL,\n"
                + "  `numero` int(20) DEFAULT NULL,\n"
                + "  `id_finca` int(50) DEFAULT NULL,\n"
                + "  `area` double DEFAULT NULL,\n"
                + "  `fecha` datetime DEFAULT NULL,\n"
                + "  `id_usuario` int(50) DEFAULT NULL\n"
                + ") ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_spanish_ci;");

        consultas.add("CREATE TABLE `cronograma` (\n"
                + "  `id` int(50) NOT NULL,\n"
                + "  `id_finca` int(50) NOT NULL,\n"
                + "  `id_actividad` int(50) NOT NULL,\n"
                + "  `anio` int(4) NOT NULL,\n"
                + "  `mes` int(2) NOT NULL,\n"
                + "  `semana` int(2) NOT NULL,\n"
                + "  `id_estado` int(20) NOT NULL,\n"
                + "  `id_usuario` int(20) DEFAULT NULL,\n"
                + "  `fecha` datetime DEFAULT NULL\n"
                + ") ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_spanish_ci;");

        consultas.add("CREATE TABLE `empleado` (\n"
                + "  `id` int(20) NOT NULL,\n"
                + "  `tipo_identificacion` varchar(100) COLLATE latin1_spanish_ci DEFAULT NULL,\n"
                + "  `identificacion` varchar(20) COLLATE latin1_spanish_ci DEFAULT NULL,\n"
                + "  `primer_nombre` varchar(50) COLLATE latin1_spanish_ci NOT NULL,\n"
                + "  `segundo_nombre` varchar(50) COLLATE latin1_spanish_ci DEFAULT NULL,\n"
                + "  `primer_apellido` varchar(50) COLLATE latin1_spanish_ci NOT NULL,\n"
                + "  `segundo_apellido` varchar(50) COLLATE latin1_spanish_ci DEFAULT NULL,\n"
                + "  `direccion` varchar(100) COLLATE latin1_spanish_ci DEFAULT NULL,\n"
                + "  `correo` varchar(100) COLLATE latin1_spanish_ci DEFAULT NULL\n"
                + ") ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_spanish_ci;");

        consultas.add("CREATE TABLE `estado_actividad` (\n"
                + "  `id` int(50) NOT NULL,\n"
                + "  `descripcion` varchar(200) COLLATE latin1_spanish_ci DEFAULT NULL,\n"
                + "  `estado` enum('Activo','Inactivo') COLLATE latin1_spanish_ci DEFAULT NULL,\n"
                + "  `color` int(100) DEFAULT NULL,\n"
                + "  `fecha_registro` datetime DEFAULT NULL,\n"
                + "  `usuario` int(50) DEFAULT NULL\n"
                + ") ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_spanish_ci;");

        consultas.add("CREATE TABLE `fincas` (\n"
                + "  `id` int(50) NOT NULL,\n"
                + "  `descripcion` text COLLATE latin1_spanish_ci DEFAULT NULL,\n"
                + "  `area` double DEFAULT NULL,\n"
                + "  `direccion` text COLLATE latin1_spanish_ci DEFAULT NULL,\n"
                + "  `id_propietario` int(50) DEFAULT NULL,\n"
                + "  `fecha` datetime DEFAULT NULL,\n"
                + "  `id_usuario` int(50) DEFAULT NULL,\n"
                + "  `id_tipo_moneda` int(20) DEFAULT NULL\n"
                + ") ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_spanish_ci;");

        consultas.add("CREATE TABLE `fuentes_hidricas` (\n"
                + "  `id` int(50) NOT NULL,\n"
                + "  `descripcion` text COLLATE latin1_spanish_ci DEFAULT NULL,\n"
                + "  `estado` enum('Activo','Inactivo') COLLATE latin1_spanish_ci DEFAULT NULL,\n"
                + "  `fecha` datetime DEFAULT NULL,\n"
                + "  `id_usuario` int(50) DEFAULT NULL\n"
                + ") ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_spanish_ci;");

        consultas.add("CREATE TABLE `grupos` (\n"
                + "  `id` int(50) NOT NULL,\n"
                + "  `id_tipo_animal` int(50) DEFAULT NULL,\n"
                + "  `descripcion` text COLLATE latin1_spanish_ci DEFAULT NULL,\n"
                + "  `estado` enum('Activo','Inactivo') COLLATE latin1_spanish_ci DEFAULT NULL,\n"
                + "  `tipo_grupo` enum('cria hembra','cria macho','descarte','muerte','default') COLLATE latin1_spanish_ci NOT NULL,\n"
                + "  `id_macrogrupo` int(50) DEFAULT NULL,\n"
                + "  `pesable` enum('0','1') COLLATE latin1_spanish_ci NOT NULL,\n"
                + "  `palpable` enum('0','1') COLLATE latin1_spanish_ci NOT NULL,\n"
                + "  `fecha` datetime DEFAULT NULL,\n"
                + "  `id_usuario` int(50) DEFAULT NULL\n"
                + ") ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_spanish_ci;");

        consultas.add("CREATE TABLE `lotes` (\n"
                + "  `id` int(50) NOT NULL,\n"
                + "  `numero` int(20) DEFAULT NULL,\n"
                + "  `id_bloque` int(50) DEFAULT NULL,\n"
                + "  `area` double DEFAULT NULL,\n"
                + "  `fecha` datetime DEFAULT NULL,\n"
                + "  `id_usuario` int(50) DEFAULT NULL\n"
                + ") ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_spanish_ci;");

        consultas.add("CREATE TABLE `lotesxestado` (\n"
                + "  `id` int(50) NOT NULL,\n"
                + "  `estado` enum('Activo','Inactivo') COLLATE latin1_spanish_ci DEFAULT NULL,\n"
                + "  `motivo` text COLLATE latin1_spanish_ci DEFAULT NULL,\n"
                + "  `fecha` datetime DEFAULT NULL,\n"
                + "  `id_usuario` int(50) DEFAULT NULL\n"
                + ") ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_spanish_ci;");

        consultas.add("CREATE TABLE `lotexfuente_hidrica` (\n"
                + "  `id` int(50) NOT NULL,\n"
                + "  `id_lote` int(50) DEFAULT NULL,\n"
                + "  `id_fuente_hidrica` int(50) DEFAULT NULL,\n"
                + "  `id_usuario` int(20) DEFAULT NULL,\n"
                + "  `fecha` datetime DEFAULT NULL\n"
                + ") ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_spanish_ci;");

        consultas.add("CREATE TABLE `macrogrupos` (\n"
                + "  `id` int(50) NOT NULL,\n"
                + "  `id_finca` int(50) NOT NULL,\n"
                + "  `descripcion` text COLLATE latin1_spanish_ci DEFAULT NULL,\n"
                + "  `estado` enum('Activo','Inactivo') COLLATE latin1_spanish_ci DEFAULT NULL,\n"
                + "  `fecha` datetime DEFAULT NULL,\n"
                + "  `id_usuario` int(50) DEFAULT NULL\n"
                + ") ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_spanish_ci;");

        consultas.add("CREATE TABLE `medicamentos` (\n"
                + "  `id` int(50) NOT NULL,\n"
                + "  `descripcion` text COLLATE latin1_spanish_ci DEFAULT NULL,\n"
                + "  `unidad_medida` varchar(50) COLLATE latin1_spanish_ci DEFAULT NULL,\n"
                + "  `estado` enum('Activo','Inactivo') COLLATE latin1_spanish_ci DEFAULT NULL,\n"
                + "  `fecha` datetime DEFAULT NULL,\n"
                + "  `id_usuario` int(50) DEFAULT NULL\n"
                + ") ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_spanish_ci;");

        consultas.add("CREATE TABLE `modulos` (\n"
                + "  `id` int(20) UNSIGNED NOT NULL,\n"
                + "  `Descripcion` varchar(100) COLLATE latin1_spanish_ci NOT NULL\n"
                + ") ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_spanish_ci;");

        consultas.add("CREATE TABLE `palpacion` (\n"
                + "  `id` int(50) NOT NULL,\n"
                + "  `id_animal` int(50) DEFAULT NULL,\n"
                + "  `fecha_palpacion` date DEFAULT NULL,\n"
                + "  `diagnostico` enum('vacia','repaso','preÃ±ada') COLLATE latin1_spanish_ci DEFAULT NULL,\n"
                + "  `notas` text COLLATE latin1_spanish_ci DEFAULT NULL,\n"
                + "  `num_meses` double DEFAULT NULL,\n"
                + "  `estado` enum('Activo','Inactivo') COLLATE latin1_spanish_ci NOT NULL,\n"
                + "  `fecha_ultimo_parto` date DEFAULT NULL,\n"
                + "  `descarte` enum('0','1') COLLATE latin1_spanish_ci DEFAULT NULL,\n"
                + "  `razondescarte` text COLLATE latin1_spanish_ci DEFAULT NULL,\n"
                + "  `fecha` date DEFAULT NULL,\n"
                + "  `id_usuario` int(50) DEFAULT NULL\n"
                + ") ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_spanish_ci;");

        consultas.add("CREATE TABLE `palpacionxtratamiento` (\n"
                + "  `id` int(50) NOT NULL,\n"
                + "  `id_palpacion` int(50) DEFAULT NULL,\n"
                + "  `id_medicamento` int(50) DEFAULT NULL,\n"
                + "  `dosis` double DEFAULT NULL\n"
                + ") ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_spanish_ci;");

        consultas.add("CREATE TABLE perfiles (\n"
                + "  id int(10) UNSIGNED NOT NULL,\n"
                + "  descripcion varchar(50) COLLATE latin1_spanish_ci NOT NULL\n"
                + ") ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_spanish_ci;");

        consultas.add("CREATE TABLE permisos (\n"
                + "  id int(20) UNSIGNED NOT NULL,\n"
                + "  tipo enum('perfil','usuario') COLLATE latin1_spanish_ci NOT NULL,\n"
                + "  valor_tipo int(50) NOT NULL,\n"
                + "  id_usuario int(50) DEFAULT NULL,\n"
                + "  fecha datetime DEFAULT NULL\n"
                + ") ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_spanish_ci;");
        consultas.add("CREATE TABLE permisosxmodulos (\n"
                + "  id int(20) UNSIGNED NOT NULL,\n"
                + "  id_permiso int(20) DEFAULT NULL,\n"
                + "  id_modulo int(20) DEFAULT NULL,\n"
                + "  s enum('0','1') COLLATE latin1_spanish_ci DEFAULT NULL,\n"
                + "  i enum('0','1') COLLATE latin1_spanish_ci DEFAULT NULL,\n"
                + "  u enum('0','1') COLLATE latin1_spanish_ci DEFAULT NULL,\n"
                + "  d enum('0','1') COLLATE latin1_spanish_ci DEFAULT NULL,\n"
                + "  v enum('0','1') COLLATE latin1_spanish_ci DEFAULT NULL,\n"
                + "  id_usuario int(50) DEFAULT NULL,\n"
                + "  fecha datetime DEFAULT NULL\n"
                + ") ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_spanish_ci;");
        consultas.add("CREATE TABLE pesaje (\n"
                + "  id int(50) NOT NULL,\n"
                + "  id_animal int(50) DEFAULT NULL,\n"
                + "  fecha_pesado date DEFAULT NULL,\n"
                + "  peso double DEFAULT NULL,\n"
                + "  peso_anterior double NOT NULL,\n"
                + "  notas text COLLATE latin1_spanish_ci,\n"
                + "  hierro enum('0','1') COLLATE latin1_spanish_ci DEFAULT NULL,\n"
                + "  descornado enum('0','1') COLLATE latin1_spanish_ci DEFAULT NULL,\n"
                + "  implante enum('0','1') COLLATE latin1_spanish_ci DEFAULT NULL,\n"
                + "  destete enum('0','1') COLLATE latin1_spanish_ci DEFAULT NULL,\n"
                + "  estado enum('Activo','Inactivo') COLLATE latin1_spanish_ci NOT NULL,\n"
                + "  fecha datetime DEFAULT NULL,\n"
                + "  id_usuario int(50) DEFAULT NULL\n"
                + ") ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_spanish_ci;");
        consultas.add("CREATE TABLE pesajexmedicamento (\n"
                + "  id int(50) NOT NULL,\n"
                + "  id_pesaje int(50) DEFAULT NULL,\n"
                + "  id_medicamento int(50) DEFAULT NULL,\n"
                + "  dosis double DEFAULT NULL\n"
                + ") ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_spanish_ci;");
        consultas.add("CREATE TABLE pluviometro (\n"
                + "  id int(20) NOT NULL,\n"
                + "  id_finca int(20) DEFAULT NULL,\n"
                + "  fecha_registro date DEFAULT NULL,\n"
                + "  cantidad double DEFAULT NULL,\n"
                + "  id_usuario int(20) DEFAULT NULL,\n"
                + "  fecha datetime DEFAULT NULL\n"
                + ") ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_spanish_ci;");
        consultas.add("CREATE TABLE propietarios (\n"
                + "  id int(50) NOT NULL,\n"
                + "  tipo_identificacion varchar(100) COLLATE latin1_spanish_ci DEFAULT NULL,\n"
                + "  identificacion varchar(100) COLLATE latin1_spanish_ci DEFAULT NULL,\n"
                + "  primer_nombre varchar(150) COLLATE latin1_spanish_ci DEFAULT NULL,\n"
                + "  segundo_nombre varchar(150) COLLATE latin1_spanish_ci DEFAULT NULL,\n"
                + "  primer_apellido varchar(150) COLLATE latin1_spanish_ci DEFAULT NULL,\n"
                + "  segundo_apellido varchar(150) COLLATE latin1_spanish_ci DEFAULT NULL,\n"
                + "  direccion text COLLATE latin1_spanish_ci,\n"
                + "  correo varchar(150) COLLATE latin1_spanish_ci DEFAULT NULL,\n"
                + "  estado enum('Activo','Inactivo') COLLATE latin1_spanish_ci DEFAULT NULL,\n"
                + "  fecha datetime DEFAULT NULL,\n"
                + "  id_usuario int(50) DEFAULT NULL\n"
                + ") ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_spanish_ci;");
        consultas.add("CREATE TABLE propietarioxhierro (\n"
                + "  id int(50) NOT NULL,\n"
                + "  id_propietario int(50) DEFAULT NULL,\n"
                + "  descripcion text COLLATE latin1_spanish_ci,\n"
                + "  nombre_imagen text COLLATE latin1_spanish_ci,\n"
                + "  imagen longtext COLLATE latin1_spanish_ci,\n"
                + "  estado enum('Activo','Inactivo') COLLATE latin1_spanish_ci DEFAULT NULL,\n"
                + "  fecha datetime DEFAULT NULL,\n"
                + "  id_usuario int(50) DEFAULT NULL\n"
                + ") ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_spanish_ci;");
        consultas.add("CREATE TABLE rotacion_lote (\n"
                + "  id int(50) NOT NULL,\n"
                + "  id_lote int(50) DEFAULT NULL,\n"
                + "  id_grupo int(50) DEFAULT NULL,\n"
                + "  fecha_registro date DEFAULT NULL,\n"
                + "  fecha_entrada date DEFAULT NULL,\n"
                + "  fecha_salida date DEFAULT NULL,\n"
                + "  estado enum('Activo','Inactivo') COLLATE latin1_spanish_ci DEFAULT NULL,\n"
                + "  fecha datetime DEFAULT NULL,\n"
                + "  id_usuario int(50) DEFAULT NULL\n"
                + ") ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_spanish_ci;");
        consultas.add("CREATE TABLE rotacion_lotesxestado (\n"
                + "  id int(50) NOT NULL,\n"
                + "  id_lote int(50) DEFAULT NULL,\n"
                + "  fecha_registro date DEFAULT NULL,\n"
                + "  fecha_entrada date DEFAULT NULL,\n"
                + "  fecha_salida date DEFAULT NULL,\n"
                + "  estado enum('Activo','Inactivo','Cancelado') COLLATE latin1_spanish_ci DEFAULT NULL,\n"
                + "  fecha datetime DEFAULT NULL,\n"
                + "  id_usuario int(50) DEFAULT NULL\n"
                + ") ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_spanish_ci;");
        consultas.add("CREATE TABLE rotacion_lotesxgrupo (\n"
                + "  id int(50) NOT NULL,\n"
                + "  id_rotacion_lotesxestado int(50) DEFAULT NULL,\n"
                + "  id_grupo int(50) DEFAULT NULL,\n"
                + "  estado enum('Activo','Inactivo','Cancelado') COLLATE latin1_spanish_ci DEFAULT 'Activo',\n"
                + "  fecha datetime DEFAULT NULL,\n"
                + "  id_usuario int(50) DEFAULT NULL\n"
                + ") ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_spanish_ci;");
        consultas.add("CREATE TABLE tipo_animales (\n"
                + "  id int(50) NOT NULL,\n"
                + "  id_finca int(50) DEFAULT NULL,\n"
                + "  descripcion text COLLATE latin1_spanish_ci,\n"
                + "  estado enum('Activo','Inactivo') COLLATE latin1_spanish_ci DEFAULT NULL,\n"
                + "  fecha datetime DEFAULT NULL,\n"
                + "  id_usuario int(50) DEFAULT NULL\n"
                + ") ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_spanish_ci;");
        consultas.add("CREATE TABLE tipo_moneda (\n"
                + "  id int(20) NOT NULL,\n"
                + "  descripcion text COLLATE latin1_spanish_ci,\n"
                + "  estado enum('Activo','Inactivo') COLLATE latin1_spanish_ci DEFAULT NULL,\n"
                + "  iniciales varchar(30) COLLATE latin1_spanish_ci DEFAULT NULL\n"
                + ") ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_spanish_ci;");
        consultas.add("CREATE TABLE traslado_animalxfinca (\n"
                + "  id int(50) NOT NULL,\n"
                + "  id_finca int(50) DEFAULT NULL,\n"
                + "  id_bloque int(50) DEFAULT NULL,\n"
                + "  id_lote int(50) DEFAULT NULL,\n"
                + "  id_animal int(50) DEFAULT NULL,\n"
                + "  estado enum('Activo','Inactivo') COLLATE latin1_spanish_ci DEFAULT NULL\n"
                + ") ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_spanish_ci;");
        consultas.add("CREATE TABLE traslado_animalxgrupo (\n"
                + "  id int(50) NOT NULL,\n"
                + "  id_animal int(50) DEFAULT NULL,\n"
                + "  id_finca int(50) DEFAULT NULL,\n"
                + "  id_grupo int(50) DEFAULT NULL,\n"
                + "  fecha_traslado date DEFAULT NULL,\n"
                + "  motivo text COLLATE latin1_spanish_ci,\n"
                + "  estado enum('Activo','Inactivo','Cancelado') COLLATE latin1_spanish_ci DEFAULT NULL,\n"
                + "  fecha datetime DEFAULT NULL,\n"
                + "  id_usuario int(50) DEFAULT NULL\n"
                + ") ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_spanish_ci;");
        consultas.add("CREATE TABLE usuarios (\n"
                + "  id int(20) NOT NULL,\n"
                + "  usuario varchar(50) COLLATE latin1_spanish_ci NOT NULL,\n"
                + "  clave varchar(100) COLLATE latin1_spanish_ci NOT NULL,\n"
                + "  clave_dinamica enum('0','1') COLLATE latin1_spanish_ci NOT NULL DEFAULT '0',\n"
                + "  estado enum('Activo','Inactivo') COLLATE latin1_spanish_ci NOT NULL DEFAULT 'Activo',\n"
                + "  id_perfil int(20) NOT NULL,\n"
                + "  id_empleado int(50) DEFAULT NULL\n"
                + ") ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_spanish_ci;");

//</editor-fold>
        
        //<editor-fold defaultstate="collapsed" desc="PRIMARY Y AUTOINCREMENT">
        consultas.add("ALTER TABLE actividades  ADD PRIMARY KEY (id);");
        consultas.add("ALTER TABLE animales  ADD PRIMARY KEY (id);");
        consultas.add("ALTER TABLE animalesxhierro  ADD PRIMARY KEY (id);");
        consultas.add("ALTER TABLE bloques  ADD PRIMARY KEY (id);");
        consultas.add("ALTER TABLE cronograma  ADD PRIMARY KEY (id);");
        consultas.add("ALTER TABLE empleado  ADD PRIMARY KEY (id);");
        consultas.add("ALTER TABLE estado_actividad  ADD PRIMARY KEY (id);");
        consultas.add("ALTER TABLE fincas  ADD PRIMARY KEY (id);");
        consultas.add("ALTER TABLE fuentes_hidricas  ADD PRIMARY KEY (id);");
        consultas.add("ALTER TABLE grupos  ADD PRIMARY KEY (id);");
        consultas.add("ALTER TABLE lotes  ADD PRIMARY KEY (id);");
        consultas.add("ALTER TABLE lotesxestado  ADD PRIMARY KEY (id);");
        consultas.add("ALTER TABLE lotexfuente_hidrica  ADD PRIMARY KEY (id);");
        consultas.add("ALTER TABLE macrogrupos  ADD PRIMARY KEY (id);");
        consultas.add("ALTER TABLE medicamentos  ADD PRIMARY KEY (id);");
        consultas.add("ALTER TABLE modulos  ADD PRIMARY KEY (id);");
        consultas.add("ALTER TABLE palpacion  ADD PRIMARY KEY (id);");
        consultas.add("ALTER TABLE palpacionxtratamiento  ADD PRIMARY KEY (id);");
        consultas.add("ALTER TABLE perfiles  ADD PRIMARY KEY (id);");
        consultas.add("ALTER TABLE permisos  ADD PRIMARY KEY (id);");
        consultas.add("ALTER TABLE permisosxmodulos  ADD PRIMARY KEY (id);");
        consultas.add("ALTER TABLE pesaje  ADD PRIMARY KEY (id);");
        consultas.add("ALTER TABLE pesajexmedicamento  ADD PRIMARY KEY (id);");
        consultas.add("ALTER TABLE pluviometro  ADD PRIMARY KEY (id);");
        consultas.add("ALTER TABLE propietarios  ADD PRIMARY KEY (id);");
        consultas.add("ALTER TABLE propietarioxhierro  ADD PRIMARY KEY (id);");
        consultas.add("ALTER TABLE rotacion_lote  ADD PRIMARY KEY (id);");
        consultas.add("ALTER TABLE rotacion_lotesxestado  ADD PRIMARY KEY (id);");
        consultas.add("ALTER TABLE rotacion_lotesxgrupo  ADD PRIMARY KEY (id);");
        consultas.add("ALTER TABLE tipo_animales  ADD PRIMARY KEY (id);");
        consultas.add("ALTER TABLE tipo_moneda  ADD PRIMARY KEY (id);");
        consultas.add("ALTER TABLE traslado_animalxfinca  ADD PRIMARY KEY (id);");
        consultas.add("ALTER TABLE traslado_animalxgrupo  ADD PRIMARY KEY (id);");
        consultas.add("ALTER TABLE usuarios  ADD PRIMARY KEY (id);");
        consultas.add("ALTER TABLE actividades  MODIFY id int(50) NOT NULL AUTO_INCREMENT;");
        consultas.add("ALTER TABLE animales  MODIFY id int(50) NOT NULL AUTO_INCREMENT;");
        consultas.add("ALTER TABLE animalesxhierro  MODIFY id int(50) NOT NULL AUTO_INCREMENT;");
        consultas.add("ALTER TABLE bloques  MODIFY id int(50) NOT NULL AUTO_INCREMENT;");
        consultas.add("ALTER TABLE cronograma  MODIFY id int(50) NOT NULL AUTO_INCREMENT;");
        consultas.add("ALTER TABLE empleado  MODIFY id int(20) NOT NULL AUTO_INCREMENT;");
        consultas.add("ALTER TABLE estado_actividad  MODIFY id int(50) NOT NULL AUTO_INCREMENT;");
        consultas.add("ALTER TABLE fincas  MODIFY id int(50) NOT NULL AUTO_INCREMENT;");
        consultas.add("ALTER TABLE fuentes_hidricas  MODIFY id int(50) NOT NULL AUTO_INCREMENT;");
        consultas.add("ALTER TABLE grupos  MODIFY id int(50) NOT NULL AUTO_INCREMENT;");
        consultas.add("ALTER TABLE lotes  MODIFY id int(50) NOT NULL AUTO_INCREMENT;");
        consultas.add("ALTER TABLE lotesxestado  MODIFY id int(50) NOT NULL AUTO_INCREMENT;");
        consultas.add("ALTER TABLE lotexfuente_hidrica  MODIFY id int(50) NOT NULL AUTO_INCREMENT;");
        consultas.add("ALTER TABLE macrogrupos  MODIFY id int(50) NOT NULL AUTO_INCREMENT;");
        consultas.add("ALTER TABLE medicamentos  MODIFY id int(50) NOT NULL AUTO_INCREMENT;");
        consultas.add("ALTER TABLE modulos  MODIFY id int(20) UNSIGNED NOT NULL AUTO_INCREMENT;");
        consultas.add("ALTER TABLE palpacion  MODIFY id int(50) NOT NULL AUTO_INCREMENT;");
        consultas.add("ALTER TABLE palpacionxtratamiento  MODIFY id int(50) NOT NULL AUTO_INCREMENT;");
        consultas.add("ALTER TABLE perfiles  MODIFY id int(10) UNSIGNED NOT NULL AUTO_INCREMENT;");
        consultas.add("ALTER TABLE permisos  MODIFY id int(20) UNSIGNED NOT NULL AUTO_INCREMENT;");
        consultas.add("ALTER TABLE permisosxmodulos  MODIFY id int(20) UNSIGNED NOT NULL AUTO_INCREMENT;");
        consultas.add("ALTER TABLE pesaje  MODIFY id int(50) NOT NULL AUTO_INCREMENT;");
        consultas.add("ALTER TABLE pesajexmedicamento  MODIFY id int(50) NOT NULL AUTO_INCREMENT;");
        consultas.add("ALTER TABLE pluviometro  MODIFY id int(20) NOT NULL AUTO_INCREMENT;");
        consultas.add("ALTER TABLE propietarios  MODIFY id int(50) NOT NULL AUTO_INCREMENT;");
        consultas.add("ALTER TABLE propietarioxhierro  MODIFY id int(50) NOT NULL AUTO_INCREMENT;");
        consultas.add("ALTER TABLE rotacion_lote  MODIFY id int(50) NOT NULL AUTO_INCREMENT;");
        consultas.add("ALTER TABLE rotacion_lotesxestado  MODIFY id int(50) NOT NULL AUTO_INCREMENT;");
        consultas.add("ALTER TABLE rotacion_lotesxgrupo  MODIFY id int(50) NOT NULL AUTO_INCREMENT;");
        consultas.add("ALTER TABLE tipo_animales  MODIFY id int(50) NOT NULL AUTO_INCREMENT;");
        consultas.add("ALTER TABLE tipo_moneda  MODIFY id int(20) NOT NULL AUTO_INCREMENT;");
        consultas.add("ALTER TABLE traslado_animalxfinca  MODIFY id int(50) NOT NULL AUTO_INCREMENT;");
        consultas.add("ALTER TABLE traslado_animalxgrupo  MODIFY id int(50) NOT NULL AUTO_INCREMENT;");
        consultas.add("ALTER TABLE usuarios  MODIFY id int(20) NOT NULL AUTO_INCREMENT;");
//</editor-fold>

        //<editor-fold defaultstate="collapsed" desc="INSERCIONES">
        consultas.add("INSERT INTO `modulos` (`id`, `Descripcion`) VALUES\n"
                + "(1, 'Propietario'),\n"
                + "(2, 'Hierros'),\n"
                + "(3, 'Finca'),\n"
                + "(4, 'Bloques'),\n"
                + "(5, 'Fuente Hidrica'),\n"
                + "(6, 'Lotes'),\n"
                + "(7, 'Pluviometro'),\n"
                + "(8, 'Macrogrupos'),\n"
                + "(9, 'Grupos'),\n"
                + "(10, 'Tipo Animales'),\n"
                + "(11, 'Agregar Animal'),\n"
                + "(12, 'Ver Animales'),\n"
                + "(13, 'Hierro por Animal'),\n"
                + "(14, 'Ventas'),\n"
                + "(15, 'Muertes'),\n"
                + "(16, 'Registro'),\n"
                + "(17, 'Estado'),\n"
                + "(18, 'Cronograma'),\n"
                + "(19, 'Medicamentos'),\n"
                + "(20, 'Pesajes'),\n"
                + "(21, 'Palpacion'),\n"
                + "(22, 'Traslado Animal'),\n"
                + "(23, 'Traslado Grupo'),\n"
                + "(24, 'Rotacion'),\n"
                + "(25, 'Analisis de Datos'),\n"
                + "(26, 'Perfiles'),\n"
                + "(27, 'Permisos'),\n"
                + "(28, 'Agregar Usuario');");

        consultas.add("INSERT INTO `empleado` (`id`, `tipo_identificacion`, `identificacion`, `primer_nombre`, `segundo_nombre`, `primer_apellido`, `segundo_apellido`, `direccion`, `correo`) VALUES\n"
                + "(1, NULL, NULL, 'RAFAEL', '', 'ZUÑIGA', NULL, NULL, 'razuac91@GMAIL.COM');");
        
        consultas.add("insert  into `perfiles`(`id`,`descripcion`) values (1,'Superadministrador');");
        
        consultas.add("INSERT INTO `permisos` (`id`, `tipo`, `valor_tipo`, `id_usuario`, `fecha`) VALUES\n" +
                        "(1, 'perfil', 1, 1, NOW());");
        
        consultas.add("INSERT INTO `permisosxmodulos` (`id`, `id_permiso`, `id_modulo`, `s`, `i`, `u`, `d`, `v`, `id_usuario`, `fecha`) VALUES\n" +
                        "(1, 1, 1, '1', '1', '1', '1', '1', 1, NOW()),\n" +
                        "(2, 1, 2, '1', '1', '1', '1', '1', 1, NOW()),\n" +
                        "(3, 1, 3, '1', '1', '1', '1', '1', 1, NOW()),\n" +
                        "(4, 1, 4, '1', '1', '1', '1', '1', 1, NOW()),\n" +
                        "(5, 1, 5, '1', '1', '1', '1', '1', 1, NOW()),\n" +
                        "(6, 1, 6, '1', '1', '1', '1', '1', 1, NOW()),\n" +
                        "(7, 1, 7, '1', '1', '1', '1', '1', 1, NOW()),\n" +
                        "(8, 1, 8, '1', '1', '1', '1', '1', 1, NOW()),\n" +
                        "(9, 1, 9, '1', '1', '1', '1', '1', 1, NOW()),\n" +
                        "(10, 1, 10, '1', '1', '1', '1', '1', 1, NOW()),\n" +
                        "(11, 1, 11, '1', '1', '1', '1', '1', 1, NOW()),\n" +
                        "(12, 1, 12, '1', '1', '1', '1', '1', 1, NOW()),\n" +
                        "(13, 1, 13, '1', '1', '1', '1', '1', 1, NOW()),\n" +
                        "(14, 1, 14, '1', '1', '1', '1', '1', 1, NOW()),\n" +
                        "(15, 1, 15, '1', '1', '1', '1', '1', 1, NOW()),\n" +
                        "(16, 1, 16, '1', '1', '1', '1', '1', 1, NOW()),\n" +
                        "(17, 1, 17, '1', '1', '1', '1', '1', 1, NOW()),\n" +
                        "(18, 1, 18, '1', '1', '1', '1', '1', 1, NOW()),\n" +
                        "(19, 1, 19, '1', '1', '1', '1', '1', 1, NOW()),\n" +
                        "(20, 1, 20, '1', '1', '1', '1', '1', 1, NOW()),\n" +
                        "(21, 1, 21, '1', '1', '1', '1', '1', 1, NOW()),\n" +
                        "(22, 1, 22, '1', '1', '1', '1', '1', 1, NOW()),\n" +
                        "(23, 1, 23, '1', '1', '1', '1', '1', 1, NOW()),\n" +
                        "(24, 1, 24, '1', '1', '1', '1', '1', 1, NOW()),\n" +
                        "(25, 1, 25, '1', '1', '1', '1', '1', 1, NOW()),\n" +
                        "(26, 1, 26, '1', '1', '1', '1', '1', 1, NOW()),\n" +
                        "(27, 1, 27, '1', '1', '1', '1', '1', 1, NOW()),\n" +
                        "(28, 1, 28, '1', '1', '1', '1', '1', 1, NOW());");
        
        consultas.add("insert  into `tipo_moneda`(`id`,`descripcion`,`estado`,`iniciales`) values (1,'Peso Colombiano','Activo','COP'),(2,'Dolar','Activo','USD'),(3,'Euro','Activo','EUR'),(4,'Yen Japones','Activo','YEN');");
        consultas.add("insert  into `usuarios`(`id`,`usuario`,`clave`,`clave_dinamica`,`estado`,`id_perfil`,`id_empleado`) values (1,'razuac','1d6ddc3d9094a728659c78c8c10b9b98','0','Activo',1,1);");
//</editor-fold> 
        
        con.EnviarConsultas(consultas);

    }
    
}
